### ISSUE TITLE
Enable/disable parts of the status bar

### ISSUE THREAD

**Issue by theblacklion** [atom/status-bar#53]
As we already know in another issue the task bar can quickly be overloaded. Also I find myself having our long feature-branch-names-with-some-stuff consume the whole status bar. Honestly, I don't need to see the branch name there. Or at least not all the time.
Would be nice if I could for example hide the branch part.
Or just don't show the name of the branch but rather give the branch symbol a tooltip having the name.
What do you think?

**Comment by simurai** [comment]
Are you thinking of having a checkbox in the settings to toggle each item?

Another option would be to hide them in your `styles.less` file. Like

```css
.status-bar .git-branch {
  display: none;
}
```

or for example if you also wanna hide the "current path" that usually takes up a lot of space:

```css
.status-bar {
  .current-path,
  .git-branch {
    display: none;
  }
}
```
